sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - "/^v?[0-9](\\.[0-9])*/"

php:
  - 5.3
  - 5.6

before_script:
  - curl https://gist.githubusercontent.com/KamataRyo/cf31b8ffe87cebae64a3acf702692e76/raw/7f9aac841b5c9be3de235b6c70c480fbdaa50c34/install-wp-tests.sh > ./install-wp-tests.sh
  - bash ./install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - npm cache clean
  - travis_retry npm install

script:
  - npm test
  - phpunit

after_success:
  - npm run generatePot
  - curl https://gist.githubusercontent.com/KamataRyo/8fd5e7b6aea4de1b3b48a5f4c429ecbe/raw/df91683e27a18e62e441fae6e0bc95b4d49d67b0/wp_plugin_deploy.sh | bash

env:
  matrix:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=3.9 WP_MULTISITE=0

  global:
    - WP_VERSION_TO_DEPLOY: latest
    - PHP_VERSION_TO_DEPLOY: 5.6
    - WP_MULTISITE_TO_DEPLOY: 0
    - GH_REF: github.com/KamataRyo/inherit-theme-mods.git
    - secure: "MOJH007gu7rUv2IjNd9yw5evCG823BCgVrUIoS2iWI0Fq4CsHcnoWqq53AeZNV0E4/GBzFM8Z3pzKCgp9s4tfZ40Gp2cOeZuBF0EbundXEnwQvDgq0QHS199XYq+W+0u3ypLuL40/REGlVnczViSIOIfFGlJ3ewdswU3N8Q8UwAlc2OiO63uGX1lr1VBDP0AG7BPr2x3DHRWLFstUWLRtOi1EV1zlkFSS9b3sAHrfQJWMV2D/5GCKhjzE6cWfuf0GQsl4tRLU2J3lFw4V5iz12afpxIn0ejllI5c45WNWx0TSWPTWuQUlUJpfnKkALWtmoCgCiT7bXbhzXcxrQTbo6XKCgRKjXw4qYmLr/YMgchNQYkX6PV6AXErbPs4mgqwnCLEH7iTdhId9eEkImC5wn0pA92YhOaybM8nv8HyFaeq4yKgIBTvzbTNy8ogiayI5cDAzlUBg22I4Ieaq/i/0yMm90fzYqRdIJj5aWAUa+izi6SKaXmYWBR8VS5OZL9EoI9v4YO35wvt/ABQlkJgWwMOkcKL6Cg/SB0H1y1ehAQ4G7rLIYgyJOHKhx4UwPtDagfS7RUTfH5ir5LoE76FMwutpv3myQZzSx9BN2TLovA4svA81u3wx1zguPMquztB2OJbJA5WrsCiRAKN9FZ4+cR4SSIvmHtVzjKvbEeR0Ls="

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=1
